// var App is a namespace to write all of our application code
var App = Ember.Application.create();
// namespace can be anything you like - but App is convention
// this single line boots ember, set up all controllers, views, and template rendering that is needed
// to see this, we'll actually need to render something - which we'll do in the HTML file
// note that this single line of code also generated the index route and controller, and renders it templates
// a single line of code does a lot

// Router

// define a bunch of URLs, each of which handle differne tactions in the application

//we define each of the resources that we are interested in
//each resource is actually a single route object
//routes can have sub routes
//NOTE App.Router - not App.Route
App.Router.map(function() {
	// '/'' => 'index'  this mapping is always generated by default - no need to specify
	this.resource('tables');
	// this will take us to the tables route - which we'll add to HTML
});
